name = "pao-ge"
main = "worker/index.js"
compatibility_date = "2025-06-25"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "paoge"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
