name = "pao-ge"
main = "worker/index.js"
compatibility_date = "2025-06-25"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "paoge"
database_id = "eb59230d-4cab-4e79-b0a9-fce660b84a35"
